spring:
  datasource:
    username: music_store
    password: music_store
    url: jdbc:mysql://localhost:3306/music_store
    
  jpa:
    hibernate: 
      ddl-auto: none
    show-sql: true
  
  sql:
    init: 
      mode: never